name: Node.js CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # use 'yarn' if you use Yarn

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          else
            npm install
          fi

      - name: Run linter (if defined)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script defined, skipping."
          fi

      - name: Run tests
        run: |
          # Replace with your test command if different
          if npm run | grep -q "test"; then
            npm test --if-present
          else
            echo "No test script defined."
          fi

      - name: Upload test results (JUnit) if present
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/test-results.xml
            **/junit.xml
